include:
  - traefik/docker-compose.yml
  - dashboard/docker-compose.yml
  - jellyfin/docker-compose.yml
  - jellyseerr/docker-compose.yml
  - servarr/docker-compose.yml
  - qbittorrent/docker-compose.yaml
  - cloudflared/docker-compose.yml

networks:
  media-network:
    driver: bridge